Update README.md
vlad-iancu/proiect-ip pull request #25
Opened 2021-11-27 12:31 UTC by vladpirlog

2021-12-16 11:20 UTC, alcxanndra commented on README.md
> +source ./venv/bin/activate
please also add the alternative Powershell command for activating the venv `./venv/Scripts/Activate.ps1`

2021-12-17 17:49 UTC, alcxanndra requested changes
Please also include the Client Requirements Analysis  Document of our project (as I understood we're required to have it on GitHub too)
https://docs.google.com/document/d/1KtePg9fmZ59uIG8FJhn2GZwhKpW8EyXxKmb-0Vsasnw/edit

2021-12-18 14:36 UTC, vladpirlog commented
> Please also include the Client Requirements Analysis Document of our project (as I understood we're required to have it on GitHub too) https://docs.google.com/document/d/1KtePg9fmZ59uIG8FJhn2GZwhKpW8EyXxKmb-0Vsasnw/edit

Added as a Google doc and wiki page.

2021-12-19 17:14 UTC, alcxanndra approved these changes

2021-12-19 17:14 UTC, merged